//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBI_eDahab.Web.eDahabServiceApi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="eDahabServiceApi.EDahabApiSouthSoap")]
    public interface EDahabApiSouthSoap {
        
        // CODEGEN: Generating message contract since message CashOutOneStepRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CashOutOneStep", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DBI_eDahab.Web.eDahabServiceApi.CashOutOneStepResponse CashOutOneStep(DBI_eDahab.Web.eDahabServiceApi.CashOutOneStepRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CashOutOneStep", ReplyAction="*")]
        System.Threading.Tasks.Task<DBI_eDahab.Web.eDahabServiceApi.CashOutOneStepResponse> CashOutOneStepAsync(DBI_eDahab.Web.eDahabServiceApi.CashOutOneStepRequest request);
        
        // CODEGEN: Generating message contract since message RegisterSubscriberRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterSubscriber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DBI_eDahab.Web.eDahabServiceApi.RegisterSubscriberResponse RegisterSubscriber(DBI_eDahab.Web.eDahabServiceApi.RegisterSubscriberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterSubscriber", ReplyAction="*")]
        System.Threading.Tasks.Task<DBI_eDahab.Web.eDahabServiceApi.RegisterSubscriberResponse> RegisterSubscriberAsync(DBI_eDahab.Web.eDahabServiceApi.RegisterSubscriberRequest request);
        
        // CODEGEN: Generating message contract since message GetCustomerInfoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DBI_eDahab.Web.eDahabServiceApi.GetCustomerInfoResponse GetCustomerInfo(DBI_eDahab.Web.eDahabServiceApi.GetCustomerInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<DBI_eDahab.Web.eDahabServiceApi.GetCustomerInfoResponse> GetCustomerInfoAsync(DBI_eDahab.Web.eDahabServiceApi.GetCustomerInfoRequest request);
        
        // CODEGEN: Generating message contract since message CheckAgentBalanceRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckAgentBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DBI_eDahab.Web.eDahabServiceApi.CheckAgentBalanceResponse CheckAgentBalance(DBI_eDahab.Web.eDahabServiceApi.CheckAgentBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckAgentBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<DBI_eDahab.Web.eDahabServiceApi.CheckAgentBalanceResponse> CheckAgentBalanceAsync(DBI_eDahab.Web.eDahabServiceApi.CheckAgentBalanceRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EDahabUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mSISDNField;
        
        private decimal balanceField;
        
        private string pwdFlagField;
        
        private string languageField;
        
        private string categoryField;
        
        private string nameField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MSISDN {
            get {
                return this.mSISDNField;
            }
            set {
                this.mSISDNField = value;
                this.RaisePropertyChanged("MSISDN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("Balance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PwdFlag {
            get {
                return this.pwdFlagField;
            }
            set {
                this.pwdFlagField = value;
                this.RaisePropertyChanged("PwdFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvivaResponseObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusCodeField;
        
        private string transactionCodeField;
        
        private string messageField;
        
        private string barredStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TransactionCode {
            get {
                return this.transactionCodeField;
            }
            set {
                this.transactionCodeField = value;
                this.RaisePropertyChanged("TransactionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BarredStatus {
            get {
                return this.barredStatusField;
            }
            set {
                this.barredStatusField = value;
                this.RaisePropertyChanged("BarredStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CashOutOneStep", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CashOutOneStepRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public DBI_eDahab.Web.eDahabServiceApi.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string msisdn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public decimal amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string input;
        
        public CashOutOneStepRequest() {
        }
        
        public CashOutOneStepRequest(DBI_eDahab.Web.eDahabServiceApi.AuthHeader AuthHeader, string msisdn, decimal amount, string input) {
            this.AuthHeader = AuthHeader;
            this.msisdn = msisdn;
            this.amount = amount;
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CashOutOneStepResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CashOutOneStepResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DBI_eDahab.Web.eDahabServiceApi.ConvivaResponseObject CashOutOneStepResult;
        
        public CashOutOneStepResponse() {
        }
        
        public CashOutOneStepResponse(DBI_eDahab.Web.eDahabServiceApi.ConvivaResponseObject CashOutOneStepResult) {
            this.CashOutOneStepResult = CashOutOneStepResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterSubscriber", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegisterSubscriberRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public DBI_eDahab.Web.eDahabServiceApi.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string msisdn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string firstname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string lastname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string gender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string city;
        
        public RegisterSubscriberRequest() {
        }
        
        public RegisterSubscriberRequest(DBI_eDahab.Web.eDahabServiceApi.AuthHeader AuthHeader, string msisdn, string firstname, string lastname, string gender, string city) {
            this.AuthHeader = AuthHeader;
            this.msisdn = msisdn;
            this.firstname = firstname;
            this.lastname = lastname;
            this.gender = gender;
            this.city = city;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterSubscriberResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegisterSubscriberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DBI_eDahab.Web.eDahabServiceApi.ConvivaResponseObject RegisterSubscriberResult;
        
        public RegisterSubscriberResponse() {
        }
        
        public RegisterSubscriberResponse(DBI_eDahab.Web.eDahabServiceApi.ConvivaResponseObject RegisterSubscriberResult) {
            this.RegisterSubscriberResult = RegisterSubscriberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomerInfoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public DBI_eDahab.Web.eDahabServiceApi.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string msisdn;
        
        public GetCustomerInfoRequest() {
        }
        
        public GetCustomerInfoRequest(DBI_eDahab.Web.eDahabServiceApi.AuthHeader AuthHeader, string msisdn) {
            this.AuthHeader = AuthHeader;
            this.msisdn = msisdn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomerInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DBI_eDahab.Web.eDahabServiceApi.EDahabUser GetCustomerInfoResult;
        
        public GetCustomerInfoResponse() {
        }
        
        public GetCustomerInfoResponse(DBI_eDahab.Web.eDahabServiceApi.EDahabUser GetCustomerInfoResult) {
            this.GetCustomerInfoResult = GetCustomerInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckAgentBalance", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckAgentBalanceRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public DBI_eDahab.Web.eDahabServiceApi.AuthHeader AuthHeader;
        
        public CheckAgentBalanceRequest() {
        }
        
        public CheckAgentBalanceRequest(DBI_eDahab.Web.eDahabServiceApi.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckAgentBalanceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckAgentBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public decimal CheckAgentBalanceResult;
        
        public CheckAgentBalanceResponse() {
        }
        
        public CheckAgentBalanceResponse(decimal CheckAgentBalanceResult) {
            this.CheckAgentBalanceResult = CheckAgentBalanceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EDahabApiSouthSoapChannel : DBI_eDahab.Web.eDahabServiceApi.EDahabApiSouthSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EDahabApiSouthSoapClient : System.ServiceModel.ClientBase<DBI_eDahab.Web.eDahabServiceApi.EDahabApiSouthSoap>, DBI_eDahab.Web.eDahabServiceApi.EDahabApiSouthSoap {
        
        public EDahabApiSouthSoapClient() {
        }
        
        public EDahabApiSouthSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EDahabApiSouthSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDahabApiSouthSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDahabApiSouthSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DBI_eDahab.Web.eDahabServiceApi.CashOutOneStepResponse DBI_eDahab.Web.eDahabServiceApi.EDahabApiSouthSoap.CashOutOneStep(DBI_eDahab.Web.eDahabServiceApi.CashOutOneStepRequest request) {
            return base.Channel.CashOutOneStep(request);
        }
        
        public DBI_eDahab.Web.eDahabServiceApi.ConvivaResponseObject CashOutOneStep(DBI_eDahab.Web.eDahabServiceApi.AuthHeader AuthHeader, string msisdn, decimal amount, string input) {
            DBI_eDahab.Web.eDahabServiceApi.CashOutOneStepRequest inValue = new DBI_eDahab.Web.eDahabServiceApi.CashOutOneStepRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.msisdn = msisdn;
            inValue.amount = amount;
            inValue.input = input;
            DBI_eDahab.Web.eDahabServiceApi.CashOutOneStepResponse retVal = ((DBI_eDahab.Web.eDahabServiceApi.EDahabApiSouthSoap)(this)).CashOutOneStep(inValue);
            return retVal.CashOutOneStepResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DBI_eDahab.Web.eDahabServiceApi.CashOutOneStepResponse> DBI_eDahab.Web.eDahabServiceApi.EDahabApiSouthSoap.CashOutOneStepAsync(DBI_eDahab.Web.eDahabServiceApi.CashOutOneStepRequest request) {
            return base.Channel.CashOutOneStepAsync(request);
        }
        
        public System.Threading.Tasks.Task<DBI_eDahab.Web.eDahabServiceApi.CashOutOneStepResponse> CashOutOneStepAsync(DBI_eDahab.Web.eDahabServiceApi.AuthHeader AuthHeader, string msisdn, decimal amount, string input) {
            DBI_eDahab.Web.eDahabServiceApi.CashOutOneStepRequest inValue = new DBI_eDahab.Web.eDahabServiceApi.CashOutOneStepRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.msisdn = msisdn;
            inValue.amount = amount;
            inValue.input = input;
            return ((DBI_eDahab.Web.eDahabServiceApi.EDahabApiSouthSoap)(this)).CashOutOneStepAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DBI_eDahab.Web.eDahabServiceApi.RegisterSubscriberResponse DBI_eDahab.Web.eDahabServiceApi.EDahabApiSouthSoap.RegisterSubscriber(DBI_eDahab.Web.eDahabServiceApi.RegisterSubscriberRequest request) {
            return base.Channel.RegisterSubscriber(request);
        }
        
        public DBI_eDahab.Web.eDahabServiceApi.ConvivaResponseObject RegisterSubscriber(DBI_eDahab.Web.eDahabServiceApi.AuthHeader AuthHeader, string msisdn, string firstname, string lastname, string gender, string city) {
            DBI_eDahab.Web.eDahabServiceApi.RegisterSubscriberRequest inValue = new DBI_eDahab.Web.eDahabServiceApi.RegisterSubscriberRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.msisdn = msisdn;
            inValue.firstname = firstname;
            inValue.lastname = lastname;
            inValue.gender = gender;
            inValue.city = city;
            DBI_eDahab.Web.eDahabServiceApi.RegisterSubscriberResponse retVal = ((DBI_eDahab.Web.eDahabServiceApi.EDahabApiSouthSoap)(this)).RegisterSubscriber(inValue);
            return retVal.RegisterSubscriberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DBI_eDahab.Web.eDahabServiceApi.RegisterSubscriberResponse> DBI_eDahab.Web.eDahabServiceApi.EDahabApiSouthSoap.RegisterSubscriberAsync(DBI_eDahab.Web.eDahabServiceApi.RegisterSubscriberRequest request) {
            return base.Channel.RegisterSubscriberAsync(request);
        }
        
        public System.Threading.Tasks.Task<DBI_eDahab.Web.eDahabServiceApi.RegisterSubscriberResponse> RegisterSubscriberAsync(DBI_eDahab.Web.eDahabServiceApi.AuthHeader AuthHeader, string msisdn, string firstname, string lastname, string gender, string city) {
            DBI_eDahab.Web.eDahabServiceApi.RegisterSubscriberRequest inValue = new DBI_eDahab.Web.eDahabServiceApi.RegisterSubscriberRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.msisdn = msisdn;
            inValue.firstname = firstname;
            inValue.lastname = lastname;
            inValue.gender = gender;
            inValue.city = city;
            return ((DBI_eDahab.Web.eDahabServiceApi.EDahabApiSouthSoap)(this)).RegisterSubscriberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DBI_eDahab.Web.eDahabServiceApi.GetCustomerInfoResponse DBI_eDahab.Web.eDahabServiceApi.EDahabApiSouthSoap.GetCustomerInfo(DBI_eDahab.Web.eDahabServiceApi.GetCustomerInfoRequest request) {
            return base.Channel.GetCustomerInfo(request);
        }
        
        public DBI_eDahab.Web.eDahabServiceApi.EDahabUser GetCustomerInfo(DBI_eDahab.Web.eDahabServiceApi.AuthHeader AuthHeader, string msisdn) {
            DBI_eDahab.Web.eDahabServiceApi.GetCustomerInfoRequest inValue = new DBI_eDahab.Web.eDahabServiceApi.GetCustomerInfoRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.msisdn = msisdn;
            DBI_eDahab.Web.eDahabServiceApi.GetCustomerInfoResponse retVal = ((DBI_eDahab.Web.eDahabServiceApi.EDahabApiSouthSoap)(this)).GetCustomerInfo(inValue);
            return retVal.GetCustomerInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DBI_eDahab.Web.eDahabServiceApi.GetCustomerInfoResponse> DBI_eDahab.Web.eDahabServiceApi.EDahabApiSouthSoap.GetCustomerInfoAsync(DBI_eDahab.Web.eDahabServiceApi.GetCustomerInfoRequest request) {
            return base.Channel.GetCustomerInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<DBI_eDahab.Web.eDahabServiceApi.GetCustomerInfoResponse> GetCustomerInfoAsync(DBI_eDahab.Web.eDahabServiceApi.AuthHeader AuthHeader, string msisdn) {
            DBI_eDahab.Web.eDahabServiceApi.GetCustomerInfoRequest inValue = new DBI_eDahab.Web.eDahabServiceApi.GetCustomerInfoRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.msisdn = msisdn;
            return ((DBI_eDahab.Web.eDahabServiceApi.EDahabApiSouthSoap)(this)).GetCustomerInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DBI_eDahab.Web.eDahabServiceApi.CheckAgentBalanceResponse DBI_eDahab.Web.eDahabServiceApi.EDahabApiSouthSoap.CheckAgentBalance(DBI_eDahab.Web.eDahabServiceApi.CheckAgentBalanceRequest request) {
            return base.Channel.CheckAgentBalance(request);
        }
        
        public decimal CheckAgentBalance(DBI_eDahab.Web.eDahabServiceApi.AuthHeader AuthHeader) {
            DBI_eDahab.Web.eDahabServiceApi.CheckAgentBalanceRequest inValue = new DBI_eDahab.Web.eDahabServiceApi.CheckAgentBalanceRequest();
            inValue.AuthHeader = AuthHeader;
            DBI_eDahab.Web.eDahabServiceApi.CheckAgentBalanceResponse retVal = ((DBI_eDahab.Web.eDahabServiceApi.EDahabApiSouthSoap)(this)).CheckAgentBalance(inValue);
            return retVal.CheckAgentBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DBI_eDahab.Web.eDahabServiceApi.CheckAgentBalanceResponse> DBI_eDahab.Web.eDahabServiceApi.EDahabApiSouthSoap.CheckAgentBalanceAsync(DBI_eDahab.Web.eDahabServiceApi.CheckAgentBalanceRequest request) {
            return base.Channel.CheckAgentBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<DBI_eDahab.Web.eDahabServiceApi.CheckAgentBalanceResponse> CheckAgentBalanceAsync(DBI_eDahab.Web.eDahabServiceApi.AuthHeader AuthHeader) {
            DBI_eDahab.Web.eDahabServiceApi.CheckAgentBalanceRequest inValue = new DBI_eDahab.Web.eDahabServiceApi.CheckAgentBalanceRequest();
            inValue.AuthHeader = AuthHeader;
            return ((DBI_eDahab.Web.eDahabServiceApi.EDahabApiSouthSoap)(this)).CheckAgentBalanceAsync(inValue);
        }
    }
}
