//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBI_eDahab.Web.DBIWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrimaryObject", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.Models.PrimaryObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.AccountInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.PentabankResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.CheckBalanceResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.AccountTransferResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.UpdateBalanceResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.CorrectTransactionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.StatementResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.GLCheckBalanceResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.ChangePINResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.SendSMSResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.PentabankRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.AccountTransferRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.UpdateBalanceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.CorrectTransactionRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.StatementRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.GLCheckBalanceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.ChangePINRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.SendSMSRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.CheckBalanceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.AccountInfoRequest))]
    public partial class PrimaryObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AccountNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AccountNo {
            get {
                return this.AccountNoField;
            }
            set {
                if ((this.AccountNoField.Equals(value) != true)) {
                    this.AccountNoField = value;
                    this.RaisePropertyChanged("AccountNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountType {
            get {
                return this.AccountTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountTypeField, value) != true)) {
                    this.AccountTypeField = value;
                    this.RaisePropertyChanged("AccountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchCode {
            get {
                return this.BranchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchCodeField, value) != true)) {
                    this.BranchCodeField = value;
                    this.RaisePropertyChanged("BranchCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionID {
            get {
                return this.TransactionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIDField, value) != true)) {
                    this.TransactionIDField = value;
                    this.RaisePropertyChanged("TransactionID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountInfo", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.Models.PrimaryObjects")]
    [System.SerializableAttribute()]
    public partial class AccountInfo : DBI_eDahab.Web.DBIWebService.PrimaryObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PentabankResponse", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.Models.PrimaryObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.CheckBalanceResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.AccountTransferResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.UpdateBalanceResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.CorrectTransactionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.StatementResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.GLCheckBalanceResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.ChangePINResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.SendSMSResponse))]
    public partial class PentabankResponse : DBI_eDahab.Web.DBIWebService.PrimaryObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdviceNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdviceNo {
            get {
                return this.AdviceNoField;
            }
            set {
                if ((object.ReferenceEquals(this.AdviceNoField, value) != true)) {
                    this.AdviceNoField = value;
                    this.RaisePropertyChanged("AdviceNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckBalanceResponse", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.Models")]
    [System.SerializableAttribute()]
    public partial class CheckBalanceResponse : DBI_eDahab.Web.DBIWebService.PentabankResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ClearBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FreezeBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ShadowBalanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ClearBalance {
            get {
                return this.ClearBalanceField;
            }
            set {
                if ((this.ClearBalanceField.Equals(value) != true)) {
                    this.ClearBalanceField = value;
                    this.RaisePropertyChanged("ClearBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FreezeBalance {
            get {
                return this.FreezeBalanceField;
            }
            set {
                if ((this.FreezeBalanceField.Equals(value) != true)) {
                    this.FreezeBalanceField = value;
                    this.RaisePropertyChanged("FreezeBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ShadowBalance {
            get {
                return this.ShadowBalanceField;
            }
            set {
                if ((this.ShadowBalanceField.Equals(value) != true)) {
                    this.ShadowBalanceField = value;
                    this.RaisePropertyChanged("ShadowBalance");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountTransferResponse", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.Models")]
    [System.SerializableAttribute()]
    public partial class AccountTransferResponse : DBI_eDahab.Web.DBIWebService.PentabankResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long OtherAccountNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtherAccountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtherBranchCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OtherPartyBalanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long OtherAccountNo {
            get {
                return this.OtherAccountNoField;
            }
            set {
                if ((this.OtherAccountNoField.Equals(value) != true)) {
                    this.OtherAccountNoField = value;
                    this.RaisePropertyChanged("OtherAccountNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherAccountType {
            get {
                return this.OtherAccountTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.OtherAccountTypeField, value) != true)) {
                    this.OtherAccountTypeField = value;
                    this.RaisePropertyChanged("OtherAccountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherBranchCode {
            get {
                return this.OtherBranchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OtherBranchCodeField, value) != true)) {
                    this.OtherBranchCodeField = value;
                    this.RaisePropertyChanged("OtherBranchCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OtherPartyBalance {
            get {
                return this.OtherPartyBalanceField;
            }
            set {
                if ((this.OtherPartyBalanceField.Equals(value) != true)) {
                    this.OtherPartyBalanceField = value;
                    this.RaisePropertyChanged("OtherPartyBalance");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateBalanceResponse", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.CorrectTransactionResponse))]
    public partial class UpdateBalanceResponse : DBI_eDahab.Web.DBIWebService.PentabankResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CustomerBalanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CustomerBalance {
            get {
                return this.CustomerBalanceField;
            }
            set {
                if ((this.CustomerBalanceField.Equals(value) != true)) {
                    this.CustomerBalanceField = value;
                    this.RaisePropertyChanged("CustomerBalance");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CorrectTransactionResponse", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.Models")]
    [System.SerializableAttribute()]
    public partial class CorrectTransactionResponse : DBI_eDahab.Web.DBIWebService.UpdateBalanceResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatementResponse", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.Models")]
    [System.SerializableAttribute()]
    public partial class StatementResponse : DBI_eDahab.Web.DBIWebService.PentabankResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ClosingBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OpeningBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DBI_eDahab.Web.DBIWebService.StatementEntity[] StatementField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ClosingBalance {
            get {
                return this.ClosingBalanceField;
            }
            set {
                if ((this.ClosingBalanceField.Equals(value) != true)) {
                    this.ClosingBalanceField = value;
                    this.RaisePropertyChanged("ClosingBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OpeningBalance {
            get {
                return this.OpeningBalanceField;
            }
            set {
                if ((this.OpeningBalanceField.Equals(value) != true)) {
                    this.OpeningBalanceField = value;
                    this.RaisePropertyChanged("OpeningBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DBI_eDahab.Web.DBIWebService.StatementEntity[] Statement {
            get {
                return this.StatementField;
            }
            set {
                if ((object.ReferenceEquals(this.StatementField, value) != true)) {
                    this.StatementField = value;
                    this.RaisePropertyChanged("Statement");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GLCheckBalanceResponse", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.Models")]
    [System.SerializableAttribute()]
    public partial class GLCheckBalanceResponse : DBI_eDahab.Web.DBIWebService.PentabankResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BalanceDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DRCRField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BalanceDate {
            get {
                return this.BalanceDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BalanceDateField, value) != true)) {
                    this.BalanceDateField = value;
                    this.RaisePropertyChanged("BalanceDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DRCR {
            get {
                return this.DRCRField;
            }
            set {
                if ((object.ReferenceEquals(this.DRCRField, value) != true)) {
                    this.DRCRField = value;
                    this.RaisePropertyChanged("DRCR");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangePINResponse", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.Models")]
    [System.SerializableAttribute()]
    public partial class ChangePINResponse : DBI_eDahab.Web.DBIWebService.PentabankResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendSMSResponse", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.Models")]
    [System.SerializableAttribute()]
    public partial class SendSMSResponse : DBI_eDahab.Web.DBIWebService.PentabankResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PentabankRequest", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.Models.PrimaryObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.AccountTransferRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.UpdateBalanceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.CorrectTransactionRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.StatementRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.GLCheckBalanceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.ChangePINRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.SendSMSRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.CheckBalanceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.AccountInfoRequest))]
    public partial class PentabankRequest : DBI_eDahab.Web.DBIWebService.PrimaryObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallerPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PINField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallerID {
            get {
                return this.CallerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CallerIDField, value) != true)) {
                    this.CallerIDField = value;
                    this.RaisePropertyChanged("CallerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallerPassword {
            get {
                return this.CallerPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.CallerPasswordField, value) != true)) {
                    this.CallerPasswordField = value;
                    this.RaisePropertyChanged("CallerPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PIN {
            get {
                return this.PINField;
            }
            set {
                if ((object.ReferenceEquals(this.PINField, value) != true)) {
                    this.PINField = value;
                    this.RaisePropertyChanged("PIN");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountTransferRequest", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.Models")]
    [System.SerializableAttribute()]
    public partial class AccountTransferRequest : DBI_eDahab.Web.DBIWebService.PentabankRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ChequeDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChequeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NarrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long OtherAccountNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtherAccountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtherBranchCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ChequeDate {
            get {
                return this.ChequeDateField;
            }
            set {
                if ((this.ChequeDateField.Equals(value) != true)) {
                    this.ChequeDateField = value;
                    this.RaisePropertyChanged("ChequeDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChequeNo {
            get {
                return this.ChequeNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ChequeNoField, value) != true)) {
                    this.ChequeNoField = value;
                    this.RaisePropertyChanged("ChequeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Narration {
            get {
                return this.NarrationField;
            }
            set {
                if ((object.ReferenceEquals(this.NarrationField, value) != true)) {
                    this.NarrationField = value;
                    this.RaisePropertyChanged("Narration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long OtherAccountNo {
            get {
                return this.OtherAccountNoField;
            }
            set {
                if ((this.OtherAccountNoField.Equals(value) != true)) {
                    this.OtherAccountNoField = value;
                    this.RaisePropertyChanged("OtherAccountNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherAccountType {
            get {
                return this.OtherAccountTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.OtherAccountTypeField, value) != true)) {
                    this.OtherAccountTypeField = value;
                    this.RaisePropertyChanged("OtherAccountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherBranchCode {
            get {
                return this.OtherBranchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OtherBranchCodeField, value) != true)) {
                    this.OtherBranchCodeField = value;
                    this.RaisePropertyChanged("OtherBranchCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateBalanceRequest", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.CorrectTransactionRequest))]
    public partial class UpdateBalanceRequest : DBI_eDahab.Web.DBIWebService.PentabankRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NarrationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Narration {
            get {
                return this.NarrationField;
            }
            set {
                if ((object.ReferenceEquals(this.NarrationField, value) != true)) {
                    this.NarrationField = value;
                    this.RaisePropertyChanged("Narration");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CorrectTransactionRequest", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.Models")]
    [System.SerializableAttribute()]
    public partial class CorrectTransactionRequest : DBI_eDahab.Web.DBIWebService.UpdateBalanceRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatementRequest", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.Models")]
    [System.SerializableAttribute()]
    public partial class StatementRequest : DBI_eDahab.Web.DBIWebService.PentabankRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FromDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoOfTransactionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OpeningBalanceFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char StatementTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ToDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FromDate {
            get {
                return this.FromDateField;
            }
            set {
                if ((this.FromDateField.Equals(value) != true)) {
                    this.FromDateField = value;
                    this.RaisePropertyChanged("FromDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoOfTransactions {
            get {
                return this.NoOfTransactionsField;
            }
            set {
                if ((this.NoOfTransactionsField.Equals(value) != true)) {
                    this.NoOfTransactionsField = value;
                    this.RaisePropertyChanged("NoOfTransactions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OpeningBalanceFlag {
            get {
                return this.OpeningBalanceFlagField;
            }
            set {
                if ((this.OpeningBalanceFlagField.Equals(value) != true)) {
                    this.OpeningBalanceFlagField = value;
                    this.RaisePropertyChanged("OpeningBalanceFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char StatementType {
            get {
                return this.StatementTypeField;
            }
            set {
                if ((this.StatementTypeField.Equals(value) != true)) {
                    this.StatementTypeField = value;
                    this.RaisePropertyChanged("StatementType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ToDate {
            get {
                return this.ToDateField;
            }
            set {
                if ((this.ToDateField.Equals(value) != true)) {
                    this.ToDateField = value;
                    this.RaisePropertyChanged("ToDate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GLCheckBalanceRequest", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.Models")]
    [System.SerializableAttribute()]
    public partial class GLCheckBalanceRequest : DBI_eDahab.Web.DBIWebService.PentabankRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangePINRequest", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.Models")]
    [System.SerializableAttribute()]
    public partial class ChangePINRequest : DBI_eDahab.Web.DBIWebService.PentabankRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MSISDNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewPINField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MSISDN {
            get {
                return this.MSISDNField;
            }
            set {
                if ((object.ReferenceEquals(this.MSISDNField, value) != true)) {
                    this.MSISDNField = value;
                    this.RaisePropertyChanged("MSISDN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewPIN {
            get {
                return this.NewPINField;
            }
            set {
                if ((object.ReferenceEquals(this.NewPINField, value) != true)) {
                    this.NewPINField = value;
                    this.RaisePropertyChanged("NewPIN");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendSMSRequest", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.Models")]
    [System.SerializableAttribute()]
    public partial class SendSMSRequest : DBI_eDahab.Web.DBIWebService.PentabankRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MSGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MSISDNField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MSG {
            get {
                return this.MSGField;
            }
            set {
                if ((object.ReferenceEquals(this.MSGField, value) != true)) {
                    this.MSGField = value;
                    this.RaisePropertyChanged("MSG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MSISDN {
            get {
                return this.MSISDNField;
            }
            set {
                if ((object.ReferenceEquals(this.MSISDNField, value) != true)) {
                    this.MSISDNField = value;
                    this.RaisePropertyChanged("MSISDN");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckBalanceRequest", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.AccountInfoRequest))]
    public partial class CheckBalanceRequest : DBI_eDahab.Web.DBIWebService.PentabankRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountInfoRequest", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.Models")]
    [System.SerializableAttribute()]
    public partial class AccountInfoRequest : DBI_eDahab.Web.DBIWebService.CheckBalanceRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatementEntity", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.Models.PrimaryObjects")]
    [System.SerializableAttribute()]
    public partial class StatementEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ChequeDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ChequeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NarrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TransactionDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ChequeDate {
            get {
                return this.ChequeDateField;
            }
            set {
                if ((this.ChequeDateField.Equals(value) != true)) {
                    this.ChequeDateField = value;
                    this.RaisePropertyChanged("ChequeDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ChequeNo {
            get {
                return this.ChequeNoField;
            }
            set {
                if ((this.ChequeNoField.Equals(value) != true)) {
                    this.ChequeNoField = value;
                    this.RaisePropertyChanged("ChequeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Narration {
            get {
                return this.NarrationField;
            }
            set {
                if ((object.ReferenceEquals(this.NarrationField, value) != true)) {
                    this.NarrationField = value;
                    this.RaisePropertyChanged("Narration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransactionDate {
            get {
                return this.TransactionDateField;
            }
            set {
                if ((this.TransactionDateField.Equals(value) != true)) {
                    this.TransactionDateField = value;
                    this.RaisePropertyChanged("TransactionDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrimaryUtilityClass", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.UtilityCalsses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.BranchesList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.CustomerAccountTypesList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.CustomerAccounts))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.Customer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DBI_eDahab.Web.DBIWebService.TransactionQuery))]
    public partial class PrimaryUtilityClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BranchesList", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.UtilityCalsses")]
    [System.SerializableAttribute()]
    public partial class BranchesList : DBI_eDahab.Web.DBIWebService.PrimaryUtilityClass {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> List {
            get {
                return this.ListField;
            }
            set {
                if ((object.ReferenceEquals(this.ListField, value) != true)) {
                    this.ListField = value;
                    this.RaisePropertyChanged("List");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerAccountTypesList", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.UtilityCalsses")]
    [System.SerializableAttribute()]
    public partial class CustomerAccountTypesList : DBI_eDahab.Web.DBIWebService.PrimaryUtilityClass {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> List {
            get {
                return this.ListField;
            }
            set {
                if ((object.ReferenceEquals(this.ListField, value) != true)) {
                    this.ListField = value;
                    this.RaisePropertyChanged("List");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerAccounts", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.UtilityCalsses")]
    [System.SerializableAttribute()]
    public partial class CustomerAccounts : DBI_eDahab.Web.DBIWebService.PrimaryUtilityClass {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DBI_eDahab.Web.DBIWebService.CustomerAccounts.DBIAccount[] AccountsListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MSISDNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DBI_eDahab.Web.DBIWebService.CustomerAccounts.DBIAccount[] AccountsList {
            get {
                return this.AccountsListField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountsListField, value) != true)) {
                    this.AccountsListField = value;
                    this.RaisePropertyChanged("AccountsList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MSISDN {
            get {
                return this.MSISDNField;
            }
            set {
                if ((object.ReferenceEquals(this.MSISDNField, value) != true)) {
                    this.MSISDNField = value;
                    this.RaisePropertyChanged("MSISDN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CustomerAccounts.DBIAccount", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.UtilityCalsses")]
        [System.SerializableAttribute()]
        public partial class DBIAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private long AccountNoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string AccountTypeField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string BranchCodeField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string CurrencyField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public long AccountNo {
                get {
                    return this.AccountNoField;
                }
                set {
                    if ((this.AccountNoField.Equals(value) != true)) {
                        this.AccountNoField = value;
                        this.RaisePropertyChanged("AccountNo");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string AccountType {
                get {
                    return this.AccountTypeField;
                }
                set {
                    if ((object.ReferenceEquals(this.AccountTypeField, value) != true)) {
                        this.AccountTypeField = value;
                        this.RaisePropertyChanged("AccountType");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string BranchCode {
                get {
                    return this.BranchCodeField;
                }
                set {
                    if ((object.ReferenceEquals(this.BranchCodeField, value) != true)) {
                        this.BranchCodeField = value;
                        this.RaisePropertyChanged("BranchCode");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Currency {
                get {
                    return this.CurrencyField;
                }
                set {
                    if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                        this.CurrencyField = value;
                        this.RaisePropertyChanged("Currency");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.UtilityCalsses")]
    [System.SerializableAttribute()]
    public partial class Customer : DBI_eDahab.Web.DBIWebService.PrimaryUtilityClass {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MSISDNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MSISDN {
            get {
                return this.MSISDNField;
            }
            set {
                if ((object.ReferenceEquals(this.MSISDNField, value) != true)) {
                    this.MSISDNField = value;
                    this.RaisePropertyChanged("MSISDN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionQuery", Namespace="http://schemas.datacontract.org/2004/07/DBIWcfService.UtilityCalsses")]
    [System.SerializableAttribute()]
    public partial class TransactionQuery : DBI_eDahab.Web.DBIWebService.PrimaryUtilityClass {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TransactionRequestTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TransactionResponseTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionID {
            get {
                return this.TransactionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIDField, value) != true)) {
                    this.TransactionIDField = value;
                    this.RaisePropertyChanged("TransactionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionMessage {
            get {
                return this.TransactionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionMessageField, value) != true)) {
                    this.TransactionMessageField = value;
                    this.RaisePropertyChanged("TransactionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransactionRequestTime {
            get {
                return this.TransactionRequestTimeField;
            }
            set {
                if ((this.TransactionRequestTimeField.Equals(value) != true)) {
                    this.TransactionRequestTimeField = value;
                    this.RaisePropertyChanged("TransactionRequestTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransactionResponseTime {
            get {
                return this.TransactionResponseTimeField;
            }
            set {
                if ((this.TransactionResponseTimeField.Equals(value) != true)) {
                    this.TransactionResponseTimeField = value;
                    this.RaisePropertyChanged("TransactionResponseTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionStatus {
            get {
                return this.TransactionStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionStatusField, value) != true)) {
                    this.TransactionStatusField = value;
                    this.RaisePropertyChanged("TransactionStatus");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DBIWebService.IDBIWebservice")]
    public interface IDBIWebservice {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/GetAccountInfo", ReplyAction="http://tempuri.org/IDBIWebservice/GetAccountInfoResponse")]
        DBI_eDahab.Web.DBIWebService.AccountInfo GetAccountInfo(DBI_eDahab.Web.DBIWebService.AccountInfoRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/GetAccountInfo", ReplyAction="http://tempuri.org/IDBIWebservice/GetAccountInfoResponse")]
        System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.AccountInfo> GetAccountInfoAsync(DBI_eDahab.Web.DBIWebService.AccountInfoRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/SearchAccount", ReplyAction="http://tempuri.org/IDBIWebservice/SearchAccountResponse")]
        DBI_eDahab.Web.DBIWebService.AccountInfo[] SearchAccount(DBI_eDahab.Web.DBIWebService.AccountInfoRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/SearchAccount", ReplyAction="http://tempuri.org/IDBIWebservice/SearchAccountResponse")]
        System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.AccountInfo[]> SearchAccountAsync(DBI_eDahab.Web.DBIWebService.AccountInfoRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/CheckBalance", ReplyAction="http://tempuri.org/IDBIWebservice/CheckBalanceResponse")]
        DBI_eDahab.Web.DBIWebService.CheckBalanceResponse CheckBalance(DBI_eDahab.Web.DBIWebService.CheckBalanceRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/CheckBalance", ReplyAction="http://tempuri.org/IDBIWebservice/CheckBalanceResponse")]
        System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.CheckBalanceResponse> CheckBalanceAsync(DBI_eDahab.Web.DBIWebService.CheckBalanceRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/AccountTransfer", ReplyAction="http://tempuri.org/IDBIWebservice/AccountTransferResponse")]
        DBI_eDahab.Web.DBIWebService.AccountTransferResponse AccountTransfer(DBI_eDahab.Web.DBIWebService.AccountTransferRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/AccountTransfer", ReplyAction="http://tempuri.org/IDBIWebservice/AccountTransferResponse")]
        System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.AccountTransferResponse> AccountTransferAsync(DBI_eDahab.Web.DBIWebService.AccountTransferRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/UpdateBalance", ReplyAction="http://tempuri.org/IDBIWebservice/UpdateBalanceResponse")]
        DBI_eDahab.Web.DBIWebService.UpdateBalanceResponse UpdateBalance(DBI_eDahab.Web.DBIWebService.UpdateBalanceRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/UpdateBalance", ReplyAction="http://tempuri.org/IDBIWebservice/UpdateBalanceResponse")]
        System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.UpdateBalanceResponse> UpdateBalanceAsync(DBI_eDahab.Web.DBIWebService.UpdateBalanceRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/ProcessFailedTransaction", ReplyAction="http://tempuri.org/IDBIWebservice/ProcessFailedTransactionResponse")]
        DBI_eDahab.Web.DBIWebService.CorrectTransactionResponse ProcessFailedTransaction(DBI_eDahab.Web.DBIWebService.CorrectTransactionRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/ProcessFailedTransaction", ReplyAction="http://tempuri.org/IDBIWebservice/ProcessFailedTransactionResponse")]
        System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.CorrectTransactionResponse> ProcessFailedTransactionAsync(DBI_eDahab.Web.DBIWebService.CorrectTransactionRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/QueryTransaction", ReplyAction="http://tempuri.org/IDBIWebservice/QueryTransactionResponse")]
        DBI_eDahab.Web.DBIWebService.TransactionQuery QueryTransaction(string req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/QueryTransaction", ReplyAction="http://tempuri.org/IDBIWebservice/QueryTransactionResponse")]
        System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.TransactionQuery> QueryTransactionAsync(string req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/GetBranchesCodes", ReplyAction="http://tempuri.org/IDBIWebservice/GetBranchesCodesResponse")]
        DBI_eDahab.Web.DBIWebService.BranchesList GetBranchesCodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/GetBranchesCodes", ReplyAction="http://tempuri.org/IDBIWebservice/GetBranchesCodesResponse")]
        System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.BranchesList> GetBranchesCodesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/GetCustomerAccountTypes", ReplyAction="http://tempuri.org/IDBIWebservice/GetCustomerAccountTypesResponse")]
        DBI_eDahab.Web.DBIWebService.CustomerAccountTypesList GetCustomerAccountTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/GetCustomerAccountTypes", ReplyAction="http://tempuri.org/IDBIWebservice/GetCustomerAccountTypesResponse")]
        System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.CustomerAccountTypesList> GetCustomerAccountTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/GetStatement", ReplyAction="http://tempuri.org/IDBIWebservice/GetStatementResponse")]
        DBI_eDahab.Web.DBIWebService.StatementResponse GetStatement(DBI_eDahab.Web.DBIWebService.StatementRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/GetStatement", ReplyAction="http://tempuri.org/IDBIWebservice/GetStatementResponse")]
        System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.StatementResponse> GetStatementAsync(DBI_eDahab.Web.DBIWebService.StatementRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/CheckGLBalance", ReplyAction="http://tempuri.org/IDBIWebservice/CheckGLBalanceResponse")]
        DBI_eDahab.Web.DBIWebService.GLCheckBalanceResponse CheckGLBalance(DBI_eDahab.Web.DBIWebService.GLCheckBalanceRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/CheckGLBalance", ReplyAction="http://tempuri.org/IDBIWebservice/CheckGLBalanceResponse")]
        System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.GLCheckBalanceResponse> CheckGLBalanceAsync(DBI_eDahab.Web.DBIWebService.GLCheckBalanceRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/GetCustomerAccounts", ReplyAction="http://tempuri.org/IDBIWebservice/GetCustomerAccountsResponse")]
        DBI_eDahab.Web.DBIWebService.CustomerAccounts GetCustomerAccounts(string msisdn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/GetCustomerAccounts", ReplyAction="http://tempuri.org/IDBIWebservice/GetCustomerAccountsResponse")]
        System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.CustomerAccounts> GetCustomerAccountsAsync(string msisdn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/VerifyCustomer", ReplyAction="http://tempuri.org/IDBIWebservice/VerifyCustomerResponse")]
        DBI_eDahab.Web.DBIWebService.Customer VerifyCustomer(string msisdn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/VerifyCustomer", ReplyAction="http://tempuri.org/IDBIWebservice/VerifyCustomerResponse")]
        System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.Customer> VerifyCustomerAsync(string msisdn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/ChangePIN", ReplyAction="http://tempuri.org/IDBIWebservice/ChangePINResponse")]
        DBI_eDahab.Web.DBIWebService.ChangePINResponse ChangePIN(DBI_eDahab.Web.DBIWebService.ChangePINRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/ChangePIN", ReplyAction="http://tempuri.org/IDBIWebservice/ChangePINResponse")]
        System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.ChangePINResponse> ChangePINAsync(DBI_eDahab.Web.DBIWebService.ChangePINRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/Send_SMS", ReplyAction="http://tempuri.org/IDBIWebservice/Send_SMSResponse")]
        DBI_eDahab.Web.DBIWebService.SendSMSResponse Send_SMS(DBI_eDahab.Web.DBIWebService.SendSMSRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBIWebservice/Send_SMS", ReplyAction="http://tempuri.org/IDBIWebservice/Send_SMSResponse")]
        System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.SendSMSResponse> Send_SMSAsync(DBI_eDahab.Web.DBIWebService.SendSMSRequest req);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDBIWebserviceChannel : DBI_eDahab.Web.DBIWebService.IDBIWebservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBIWebserviceClient : System.ServiceModel.ClientBase<DBI_eDahab.Web.DBIWebService.IDBIWebservice>, DBI_eDahab.Web.DBIWebService.IDBIWebservice {
        
        public DBIWebserviceClient() {
        }
        
        public DBIWebserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBIWebserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBIWebserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBIWebserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DBI_eDahab.Web.DBIWebService.AccountInfo GetAccountInfo(DBI_eDahab.Web.DBIWebService.AccountInfoRequest req) {
            return base.Channel.GetAccountInfo(req);
        }
        
        public System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.AccountInfo> GetAccountInfoAsync(DBI_eDahab.Web.DBIWebService.AccountInfoRequest req) {
            return base.Channel.GetAccountInfoAsync(req);
        }
        
        public DBI_eDahab.Web.DBIWebService.AccountInfo[] SearchAccount(DBI_eDahab.Web.DBIWebService.AccountInfoRequest req) {
            return base.Channel.SearchAccount(req);
        }
        
        public System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.AccountInfo[]> SearchAccountAsync(DBI_eDahab.Web.DBIWebService.AccountInfoRequest req) {
            return base.Channel.SearchAccountAsync(req);
        }
        
        public DBI_eDahab.Web.DBIWebService.CheckBalanceResponse CheckBalance(DBI_eDahab.Web.DBIWebService.CheckBalanceRequest req) {
            return base.Channel.CheckBalance(req);
        }
        
        public System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.CheckBalanceResponse> CheckBalanceAsync(DBI_eDahab.Web.DBIWebService.CheckBalanceRequest req) {
            return base.Channel.CheckBalanceAsync(req);
        }
        
        public DBI_eDahab.Web.DBIWebService.AccountTransferResponse AccountTransfer(DBI_eDahab.Web.DBIWebService.AccountTransferRequest req) {
            return base.Channel.AccountTransfer(req);
        }
        
        public System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.AccountTransferResponse> AccountTransferAsync(DBI_eDahab.Web.DBIWebService.AccountTransferRequest req) {
            return base.Channel.AccountTransferAsync(req);
        }
        
        public DBI_eDahab.Web.DBIWebService.UpdateBalanceResponse UpdateBalance(DBI_eDahab.Web.DBIWebService.UpdateBalanceRequest req) {
            return base.Channel.UpdateBalance(req);
        }
        
        public System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.UpdateBalanceResponse> UpdateBalanceAsync(DBI_eDahab.Web.DBIWebService.UpdateBalanceRequest req) {
            return base.Channel.UpdateBalanceAsync(req);
        }
        
        public DBI_eDahab.Web.DBIWebService.CorrectTransactionResponse ProcessFailedTransaction(DBI_eDahab.Web.DBIWebService.CorrectTransactionRequest req) {
            return base.Channel.ProcessFailedTransaction(req);
        }
        
        public System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.CorrectTransactionResponse> ProcessFailedTransactionAsync(DBI_eDahab.Web.DBIWebService.CorrectTransactionRequest req) {
            return base.Channel.ProcessFailedTransactionAsync(req);
        }
        
        public DBI_eDahab.Web.DBIWebService.TransactionQuery QueryTransaction(string req) {
            return base.Channel.QueryTransaction(req);
        }
        
        public System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.TransactionQuery> QueryTransactionAsync(string req) {
            return base.Channel.QueryTransactionAsync(req);
        }
        
        public DBI_eDahab.Web.DBIWebService.BranchesList GetBranchesCodes() {
            return base.Channel.GetBranchesCodes();
        }
        
        public System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.BranchesList> GetBranchesCodesAsync() {
            return base.Channel.GetBranchesCodesAsync();
        }
        
        public DBI_eDahab.Web.DBIWebService.CustomerAccountTypesList GetCustomerAccountTypes() {
            return base.Channel.GetCustomerAccountTypes();
        }
        
        public System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.CustomerAccountTypesList> GetCustomerAccountTypesAsync() {
            return base.Channel.GetCustomerAccountTypesAsync();
        }
        
        public DBI_eDahab.Web.DBIWebService.StatementResponse GetStatement(DBI_eDahab.Web.DBIWebService.StatementRequest req) {
            return base.Channel.GetStatement(req);
        }
        
        public System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.StatementResponse> GetStatementAsync(DBI_eDahab.Web.DBIWebService.StatementRequest req) {
            return base.Channel.GetStatementAsync(req);
        }
        
        public DBI_eDahab.Web.DBIWebService.GLCheckBalanceResponse CheckGLBalance(DBI_eDahab.Web.DBIWebService.GLCheckBalanceRequest req) {
            return base.Channel.CheckGLBalance(req);
        }
        
        public System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.GLCheckBalanceResponse> CheckGLBalanceAsync(DBI_eDahab.Web.DBIWebService.GLCheckBalanceRequest req) {
            return base.Channel.CheckGLBalanceAsync(req);
        }
        
        public DBI_eDahab.Web.DBIWebService.CustomerAccounts GetCustomerAccounts(string msisdn) {
            return base.Channel.GetCustomerAccounts(msisdn);
        }
        
        public System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.CustomerAccounts> GetCustomerAccountsAsync(string msisdn) {
            return base.Channel.GetCustomerAccountsAsync(msisdn);
        }
        
        public DBI_eDahab.Web.DBIWebService.Customer VerifyCustomer(string msisdn) {
            return base.Channel.VerifyCustomer(msisdn);
        }
        
        public System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.Customer> VerifyCustomerAsync(string msisdn) {
            return base.Channel.VerifyCustomerAsync(msisdn);
        }
        
        public DBI_eDahab.Web.DBIWebService.ChangePINResponse ChangePIN(DBI_eDahab.Web.DBIWebService.ChangePINRequest req) {
            return base.Channel.ChangePIN(req);
        }
        
        public System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.ChangePINResponse> ChangePINAsync(DBI_eDahab.Web.DBIWebService.ChangePINRequest req) {
            return base.Channel.ChangePINAsync(req);
        }
        
        public DBI_eDahab.Web.DBIWebService.SendSMSResponse Send_SMS(DBI_eDahab.Web.DBIWebService.SendSMSRequest req) {
            return base.Channel.Send_SMS(req);
        }
        
        public System.Threading.Tasks.Task<DBI_eDahab.Web.DBIWebService.SendSMSResponse> Send_SMSAsync(DBI_eDahab.Web.DBIWebService.SendSMSRequest req) {
            return base.Channel.Send_SMSAsync(req);
        }
    }
}
